// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.CZ.Data.EFCore;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(CesiZenDbContext))]
    [Migration("20260401171557_AddUserIdToUserSavedConfigurations")]
    partial class AddUserIdToUserSavedConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdSession")
                        .HasColumnType("uuid")
                        .HasColumnName("id_session");

                    b.HasKey("Id", "IdSession")
                        .HasName("auth_pk");

                    b.HasIndex("IdSession");

                    b.ToTable("auth", (string)null);
                });

            modelBuilder.Entity("Tagged", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdInformationTags")
                        .HasColumnType("uuid")
                        .HasColumnName("id_information_tags");

                    b.HasKey("Id", "IdInformationTags")
                        .HasName("tagged_pk");

                    b.HasIndex("IdInformationTags");

                    b.ToTable("tagged", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.AdminEmailConfirmationTokens.Models.AdminEmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdAdministrators")
                        .HasColumnType("uuid")
                        .HasColumnName("id_administrators");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("admin_email_confirmation_tokens_pk");

                    b.HasIndex("IdAdministrators");

                    b.ToTable("admin_email_confirmation_tokens", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.AdminLogs.Models.AdminLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("IdAdministrator")
                        .HasColumnType("uuid")
                        .HasColumnName("id_administrator");

                    b.Property<Guid>("TargetedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("targeted_entity_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("admin_logs_pk");

                    b.HasIndex("IdAdministrator");

                    b.ToTable("admin_logs", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.AdminPasswordResetTokens.Models.AdminPasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdAdministrators")
                        .HasColumnType("uuid")
                        .HasColumnName("id_administrators");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("admin_password_reset_tokens_pk");

                    b.HasIndex("IdAdministrators");

                    b.HasIndex(new[] { "Token" }, "admin_token_idx");

                    b.ToTable("admin_password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.AdminSessions.Models.AdminSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdAdministrators")
                        .HasColumnType("uuid")
                        .HasColumnName("id_administrators");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("admin_session_pk");

                    b.HasIndex("IdAdministrators");

                    b.ToTable("admin_session", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.Administrators.Models.Administrator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AccountActivated")
                        .HasColumnType("boolean")
                        .HasColumnName("account_activated");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("IdNavigationMenu")
                        .HasColumnType("uuid")
                        .HasColumnName("id_navigation_menu");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("member_since");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("administrators_pk");

                    b.HasIndex("IdNavigationMenu");

                    b.HasIndex(new[] { "Email" }, "email_admin_idx");

                    b.HasIndex(new[] { "Email" }, "email_admin_unq")
                        .IsUnique();

                    b.ToTable("administrators", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.Bookmarks.Models.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdConfigurations")
                        .HasColumnType("uuid")
                        .HasColumnName("id_configurations");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id", "IdConfigurations")
                        .HasName("bookmark_pk");

                    b.HasIndex("IdConfigurations");

                    b.ToTable("bookmark", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.Configurations.Models.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("Exhalation")
                        .HasColumnType("integer")
                        .HasColumnName("exhalation");

                    b.Property<string>("GuidanceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guidance_type");

                    b.Property<Guid>("IdAdministrators")
                        .HasColumnType("uuid")
                        .HasColumnName("id_administrators");

                    b.Property<int>("Inhalation")
                        .HasColumnType("integer")
                        .HasColumnName("inhalation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("objective");

                    b.Property<int>("Retention1")
                        .HasColumnType("integer")
                        .HasColumnName("retention1");

                    b.Property<int>("Retention2")
                        .HasColumnType("integer")
                        .HasColumnName("retention2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("configurations_pk");

                    b.HasIndex("IdAdministrators");

                    b.ToTable("configurations", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.EmailConfirmationTokens.Models.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdUsers")
                        .HasColumnType("uuid")
                        .HasColumnName("id_users");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("email_confirmation_tokens_pk");

                    b.HasIndex("IdUsers");

                    b.ToTable("email_confirmation_tokens", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.InformationPages.Models.InformationPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<bool>("CurrentlyEditing")
                        .HasColumnType("boolean")
                        .HasColumnName("currently_editing");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("IdAdministrators")
                        .HasColumnType("uuid")
                        .HasColumnName("id_administrators");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("information_pages_pk");

                    b.HasIndex("IdAdministrators");

                    b.ToTable("information_pages", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.InformationTags.Models.InformationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("information_tags_pk");

                    b.ToTable("information_tags", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.NavigationMenus.Models.NavigationMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<bool>("CurrentlyEditing")
                        .HasColumnType("boolean")
                        .HasColumnName("currently_editing");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("navigation_menu_pk");

                    b.HasIndex("ParentId");

                    b.ToTable("navigation_menu", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.PasswordHistories.Models.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changed_at");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<Guid>("IdPasswordsInfos")
                        .HasColumnType("uuid")
                        .HasColumnName("id_passwords_infos");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("password_history_pk");

                    b.HasIndex("IdPasswordsInfos");

                    b.ToTable("password_history", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.PasswordResetTokens.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdUsers")
                        .HasColumnType("uuid")
                        .HasColumnName("id_users");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("password_reset_tokens_pk");

                    b.HasIndex("IdUsers");

                    b.HasIndex(new[] { "Token" }, "token_idx");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.PasswordsInfos.Models.PasswordsInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login");

                    b.Property<DateTime>("LastReset")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_reset");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("passwords_infos_pk");

                    b.ToTable("passwords_infos", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.Quizzes.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<Guid>("IdQuizz")
                        .HasColumnType("uuid")
                        .HasColumnName("id_quizz");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("questions_pk");

                    b.HasIndex("IdQuizz");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.Quizzes.Models.Quizz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("quizz_pk");

                    b.ToTable("quizz", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.Quizzes.Models.ResponsesOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<Guid>("IdQuestions")
                        .HasColumnType("uuid")
                        .HasColumnName("id_questions");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("operation");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("TargetedField")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("targeted_field");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("responses_options_pk");

                    b.HasIndex("IdQuestions");

                    b.ToTable("responses_options", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.Sessions.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdUsers")
                        .HasColumnType("uuid")
                        .HasColumnName("id_users");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("session_pk");

                    b.HasIndex("IdUsers");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.UserSavedConfigurations.Models.UserSavedConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("Exhalation")
                        .HasColumnType("integer")
                        .HasColumnName("exhalation");

                    b.Property<string>("GuidanceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guidance_type");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<int>("Inhalation")
                        .HasColumnType("integer")
                        .HasColumnName("inhalation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("objective");

                    b.Property<int>("Retention1")
                        .HasColumnType("integer")
                        .HasColumnName("retention1");

                    b.Property<int>("Retention2")
                        .HasColumnType("integer")
                        .HasColumnName("retention2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("user_saved_configurations_pk");

                    b.HasIndex("IdUser");

                    b.ToTable("user_saved_configurations", (string)null);
                });

            modelBuilder.Entity("api.CZ.Features.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AccountActivated")
                        .HasColumnType("boolean")
                        .HasColumnName("account_activated");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("IdPasswordsInfos")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdPasswordsInfosNavigationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUserSavedConfigurations")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user_saved_configurations");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("member_since");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("users_pk");

                    b.HasIndex("IdPasswordsInfosNavigationId");

                    b.HasIndex("IdUserSavedConfigurations");

                    b.HasIndex(new[] { "Email" }, "email_idx");

                    b.HasIndex(new[] { "Email" }, "email_unq")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Auth", b =>
                {
                    b.HasOne("api.CZ.Features.Administrators.Models.Administrator", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .IsRequired()
                        .HasConstraintName("auth_id_fk");

                    b.HasOne("api.CZ.Features.Sessions.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("IdSession")
                        .IsRequired()
                        .HasConstraintName("auth_id_session_fk");
                });

            modelBuilder.Entity("Tagged", b =>
                {
                    b.HasOne("api.CZ.Features.InformationPages.Models.InformationPage", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .IsRequired()
                        .HasConstraintName("tagged_id_fk");

                    b.HasOne("api.CZ.Features.InformationTags.Models.InformationTag", null)
                        .WithMany()
                        .HasForeignKey("IdInformationTags")
                        .IsRequired()
                        .HasConstraintName("tagged_id_information_tags_fk");
                });

            modelBuilder.Entity("api.CZ.Features.AdminEmailConfirmationTokens.Models.AdminEmailConfirmationToken", b =>
                {
                    b.HasOne("api.CZ.Features.Administrators.Models.Administrator", "IdAdministratorsNavigation")
                        .WithMany("AdminEmailConfirmationTokens")
                        .HasForeignKey("IdAdministrators")
                        .IsRequired()
                        .HasConstraintName("admin_email_confirmation_tokens_id_administrators_fk");

                    b.Navigation("IdAdministratorsNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.AdminLogs.Models.AdminLog", b =>
                {
                    b.HasOne("api.CZ.Features.Administrators.Models.Administrator", "IdAdministratorNavigation")
                        .WithMany("AdminLogs")
                        .HasForeignKey("IdAdministrator")
                        .IsRequired()
                        .HasConstraintName("admin_logs_id_administrator_fk");

                    b.Navigation("IdAdministratorNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.AdminPasswordResetTokens.Models.AdminPasswordResetToken", b =>
                {
                    b.HasOne("api.CZ.Features.Administrators.Models.Administrator", "IdAdministratorsNavigation")
                        .WithMany("AdminPasswordResetTokens")
                        .HasForeignKey("IdAdministrators")
                        .IsRequired()
                        .HasConstraintName("admin_password_reset_tokens_id_administrators_fk");

                    b.Navigation("IdAdministratorsNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.AdminSessions.Models.AdminSession", b =>
                {
                    b.HasOne("api.CZ.Features.Administrators.Models.Administrator", "IdAdministratorsNavigation")
                        .WithMany("AdminSessions")
                        .HasForeignKey("IdAdministrators")
                        .IsRequired()
                        .HasConstraintName("admin_session_id_administrators_fk");

                    b.Navigation("IdAdministratorsNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.Administrators.Models.Administrator", b =>
                {
                    b.HasOne("api.CZ.Features.NavigationMenus.Models.NavigationMenu", "IdNavigationMenuNavigation")
                        .WithMany("Administrators")
                        .HasForeignKey("IdNavigationMenu")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("administrators_id_navigation_menu_fk");

                    b.Navigation("IdNavigationMenuNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.Bookmarks.Models.Bookmark", b =>
                {
                    b.HasOne("api.CZ.Features.Users.Models.User", "IdNavigation")
                        .WithMany("Bookmarks")
                        .HasForeignKey("Id")
                        .IsRequired()
                        .HasConstraintName("bookmark_id_fk");

                    b.HasOne("api.CZ.Features.Configurations.Models.Configuration", "IdConfigurationsNavigation")
                        .WithMany("Bookmarks")
                        .HasForeignKey("IdConfigurations")
                        .IsRequired()
                        .HasConstraintName("bookmark_id_configurations_fk");

                    b.Navigation("IdConfigurationsNavigation");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.Configurations.Models.Configuration", b =>
                {
                    b.HasOne("api.CZ.Features.Administrators.Models.Administrator", "IdAdministratorsNavigation")
                        .WithMany("Configurations")
                        .HasForeignKey("IdAdministrators")
                        .IsRequired()
                        .HasConstraintName("configurations_id_administrators_fk");

                    b.Navigation("IdAdministratorsNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.EmailConfirmationTokens.Models.EmailConfirmationToken", b =>
                {
                    b.HasOne("api.CZ.Features.Users.Models.User", "IdUsersNavigation")
                        .WithMany("EmailConfirmationTokens")
                        .HasForeignKey("IdUsers")
                        .IsRequired()
                        .HasConstraintName("email_confirmation_tokens_id_users_fk");

                    b.Navigation("IdUsersNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.InformationPages.Models.InformationPage", b =>
                {
                    b.HasOne("api.CZ.Features.Administrators.Models.Administrator", "IdAdministratorsNavigation")
                        .WithMany("InformationPages")
                        .HasForeignKey("IdAdministrators")
                        .IsRequired()
                        .HasConstraintName("information_pages_id_administrators_fk");

                    b.Navigation("IdAdministratorsNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.NavigationMenus.Models.NavigationMenu", b =>
                {
                    b.HasOne("api.CZ.Features.NavigationMenus.Models.NavigationMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("api.CZ.Features.PasswordHistories.Models.PasswordHistory", b =>
                {
                    b.HasOne("api.CZ.Features.PasswordsInfos.Models.PasswordsInfo", "IdPasswordsInfosNavigation")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("IdPasswordsInfos")
                        .IsRequired()
                        .HasConstraintName("password_history_id_passwords_infos_fk");

                    b.Navigation("IdPasswordsInfosNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.PasswordResetTokens.Models.PasswordResetToken", b =>
                {
                    b.HasOne("api.CZ.Features.Users.Models.User", "IdUsersNavigation")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("IdUsers")
                        .IsRequired()
                        .HasConstraintName("password_reset_tokens_id_users_fk");

                    b.Navigation("IdUsersNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.Quizzes.Models.Question", b =>
                {
                    b.HasOne("api.CZ.Features.Quizzes.Models.Quizz", "IdQuizzNavigation")
                        .WithMany("Questions")
                        .HasForeignKey("IdQuizz")
                        .IsRequired()
                        .HasConstraintName("questions_id_quizz_fk");

                    b.Navigation("IdQuizzNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.Quizzes.Models.ResponsesOption", b =>
                {
                    b.HasOne("api.CZ.Features.Quizzes.Models.Question", "IdQuestionsNavigation")
                        .WithMany("ResponsesOptions")
                        .HasForeignKey("IdQuestions")
                        .IsRequired()
                        .HasConstraintName("responses_options_id_questions_fk");

                    b.Navigation("IdQuestionsNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.Sessions.Models.Session", b =>
                {
                    b.HasOne("api.CZ.Features.Users.Models.User", "IdUsersNavigation")
                        .WithMany("Sessions")
                        .HasForeignKey("IdUsers")
                        .IsRequired()
                        .HasConstraintName("session_id_users_fk");

                    b.Navigation("IdUsersNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.UserSavedConfigurations.Models.UserSavedConfiguration", b =>
                {
                    b.HasOne("api.CZ.Features.Users.Models.User", "IdUserNavigation")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("user_saved_configurations_id_user_fk");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.Users.Models.User", b =>
                {
                    b.HasOne("api.CZ.Features.PasswordsInfos.Models.PasswordsInfo", "IdPasswordsInfosNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdPasswordsInfosNavigationId");

                    b.HasOne("api.CZ.Features.UserSavedConfigurations.Models.UserSavedConfiguration", "IdUserSavedConfigurationsNavigation")
                        .WithMany()
                        .HasForeignKey("IdUserSavedConfigurations")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("users_id_user_saved_configurations_fk");

                    b.Navigation("IdPasswordsInfosNavigation");

                    b.Navigation("IdUserSavedConfigurationsNavigation");
                });

            modelBuilder.Entity("api.CZ.Features.Administrators.Models.Administrator", b =>
                {
                    b.Navigation("AdminEmailConfirmationTokens");

                    b.Navigation("AdminLogs");

                    b.Navigation("AdminPasswordResetTokens");

                    b.Navigation("AdminSessions");

                    b.Navigation("Configurations");

                    b.Navigation("InformationPages");
                });

            modelBuilder.Entity("api.CZ.Features.Configurations.Models.Configuration", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("api.CZ.Features.NavigationMenus.Models.NavigationMenu", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("api.CZ.Features.PasswordsInfos.Models.PasswordsInfo", b =>
                {
                    b.Navigation("PasswordHistories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("api.CZ.Features.Quizzes.Models.Question", b =>
                {
                    b.Navigation("ResponsesOptions");
                });

            modelBuilder.Entity("api.CZ.Features.Quizzes.Models.Quizz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("api.CZ.Features.Users.Models.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("EmailConfirmationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
